.TH SAH 8 "February 12, 2019" "version 0.7.3" "SAH Manual"
.SH NAME
Simple AUR Helper (SAH) and Pacman wrapper
.SH SYNOPSIS
.B sah
<operation> [packages]
.SH DESCRIPTION
Simple AUR Helper and Pacman wrapper
.SH OPERATIONS
.B -S, install
.RS
Install package/packages from AUR
.RE
.B -Sp
.RS
Install package/packages from Pacman
.RE
.B -Sf
.RS
Install packages from file with list of packages (AUR)
.RE
.B -Spf
.RS
Install packages from file with list of packages (Pacman)
.RE
.B -U
.RS
Install local or remote package
.RE
.B -Syy, update
.RS
Update package database
.RE
.B -Syu, upgrade
.RS
Update installed packages (Pacman + AUR)
.RE
.B -Sc, autoremove
.RS
Clean the package cache
.RE
.B -R, remove
.RS
Remove package/packages
.RE
.B -Rs, purge
.RS
Remove package/packages with dependencies which aren't required by any other installed packages
.RE
.B -Q, list
.RS
Show installed packages (All)
.RE
.B -Qe
.RS
Show installed packages (Explicitly)
.RE
.B -Qm
.RS
Show installed packages (AUR)
.RE
.B -Ss
.RS
Search for packages in the database
.RE
.B -Qs
.RS
Search for already installed packages
.RE
.B -Si
.RS
Show information about package
.RE
.B -Qi
.RS
Show information about package (for locally installed packages)
.RE
.B -Qdt
.RS
Show all packages no longer required as dependencies (orphans)
.RE
.SH OPTIONS
.B custom [operation]
.RS
Execute custom Pacman operation
.RE
.B stat
.RS
Show packages statistics
.RE
.B config
.RS
Open SAH config file via nano editor
.RE
.B resetconfig
.RS
Reset to default SAH config file from GitHub repo
.RE
.B pacconf
.RS
Open Pacman config file via nano editor
.RE
.B mirrorlist
.RS
Open mirrorlist file via nano editor
.RE
.B updatemirrors
.RS
Update mirrorlist from Arch Linux website
.RE
.B changelog
.RS
Show SAH changelog
.RE
.B top
.RS
Show AUR TOP-10 packages
.RE
.B top [1-10]
.RS
Install package from AUR TOP-10
.RE
.B log
.RS
Show SAH log (if logging is enabled)
.RE
.B clearlog
.RS
Clear SAH log file (if logging is enabled)
.RE
.SH CONFIGURATION
You can edit SAH config file to set up some settings
.PP
SAH config file path:
.B /etc/sah_config
.PP
Also you can use 'sah config' to open SAH config file via nano editor
.PP
.B Supported properties in config:
.PP
.B logging (true/false)
.RS
enable/disable logging
.RE
.B editor (editor name)
.RS
text editor for editing configs
.RE
.B update_pacman (true/false)
.RS
enable/disable updating of Pacman packages
.RE
.B update_aur (true/false)
.RS
enable/disable updating of AUR packages
.RE
.B aur_update_notify (true/false)
.RS
notify about new versions of AUR packages during updating
.RE
.B aur_update_ignore (package1,package2,...)
.RS
skip updating of some AUR packages
.RE
.B mirrorlist_country (country code)
.RS
mirrors country
.RE
.B mirrorlist_protocol (http/https)
.RS
mirrors protocol
.RE
.B mirrorlist_ip_version (4/6)
.RS
mirrors IP version
.RE
.B rmd (true/false)
.RS
remove make dependencies of AUR packages during installation or updating
.RE
.B pgp_check (true/false)
.RS
enable/disable verifying PGP signatures of source files
.RE
.B needed (true/false)
.RS
enable/disable reinstalling packages if they are already up-to-date
.RE
.B noconfirm (true/false)
.RS
enable/disable waiting for user input before proceeding with operations
.RE
.PP
.B Properties examples:
.PP
logging=true
.PP
editor=nano
.PP
update_pacman=true
.PP
update_aur=true
.PP
aur_update_notify=false
.PP
aur_update_ignore=yay,dropbox,google-chrome
.PP
mirrorlist_country=RU
.PP
mirrorlist_protocol=http
.PP
mirrorlist_ip_version=4
.PP
rmd=false
.PP
pgp_check=false
.PP
needed=false
.PP
noconfirm=false
.SH EXAMPLES
Install package/packages from AUR
.RS
.B sah
-S [package1] [package2] ...
.RE
Install package/packages from Pacman
.RS
.B sah
-Sp [package1] [package2] ...
.RE
Install local package
.RS
.B sah
-U /path/to/package/package_name-version.pkg.tar.xz
.RE
Install remote package
.RS
.B sah
-U https://www.example.com/repo/example.pkg.tar.xz
.RE
Update installed packages (Pacman + AUR)
.RS
.B sah
-Syu
.RE
Execute custom Pacman operation (-Syyu)
.RS
.B sah
custom -Syyu
.RE
Execute custom Pacman operation (-Syu and install a package)
.RS
.B sah
custom -Syu chromium
.RE
Install package from AUR TOP-10 (7th)
.RS
.B sah
top 7
.RE
.SH AUTHOR
Stepan Skryabin
.SH "SEE ALSO"
pacman(8)
