.TH SAH 8 "February 12, 2019" "version 0.4.3" "SAH Manual"
.SH NAME
Simple AUR Helper (SAH)
.SH SYNOPSIS
.B sah
<operation> [packages] [options]
.SH DESCRIPTION
Simple AUR Helper
.SH OPERATIONS
.B -S
.RS
Install package/packages from AUR
.RE
.B -Sp
.RS
Install package/packages from Pacman
.RE
.B -Syu
.RS
Update installed packages (Pacman + AUR)
.RE
.B -Sc
.RS
Clean the package cache
.RE
.B -R
.RS
Remove package/packages
.RE
.B -Rs
.RS
Remove package/packages with dependencies which aren't required by any other installed packages
.RE
.B -Qe
.RS
Show installed packages (All)
.RE
.B -Qm
.RS
Show installed packages (AUR)
.RE
.B -Ss
.RS
Search for packages in the database
.RE
.B -Qs
.RS
Search for already installed packages
.RE
.B -Si
.RS
Show information about package
.RE
.B -Qi
.RS
Show information about package (for locally installed packages)
.RE
.B -Qdt
.RS
Show all packages no longer required as dependencies (orphans)
.RE
.SH OPTIONS
.B config
.RS
Open config file via nano editor
.RE
.B changelog
.RS
Show SAH changelog
.RE
.SH CONFIGURATION
You can edit SAH config file to set up some settings
.PP
SAH config file path:
.B /etc/sah_config
.PP
Also you can use 'sah config' to open config file via nano editor
.PP
.B Supported properties in config:
.PP
aur_update_ignore (package1,package2,...) - skip updating of some AUR packages
.PP
rmd (true/false) - remove make dependencies of AUR packages during installation or updating
.PP
pgp_check (true/false) - enable/disable verifying PGP signatures of source files
.PP
needed (true/false) - enable/disable reinstalling packages if they are already up-to-date
.PP
.B Properties examples:
.PP
aur_update_ignore=yay,dropbox,google-chrome
.PP
rmd=false
.PP
pgp_check=false
.PP
needed=false
.SH EXAMPLES
Install package/packages from AUR
.RS
.B sah
-S [package1] [package2] ...
.RE
Update installed packages (Pacman + AUR)
.RS
.B sah
-Syu
.RE
.SH AUTHOR
Stepan Skryabin
.SH "SEE ALSO"
pacman(8)
